name: My Sample Docker test

on: pull_request

jobs:
  phpcs:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH access to Pantheon
      run: |
        # define settings here
        ls

# learn how to build own Docker
# execute scripts in it
# add phpcs
# build steps
# slackbot integration